import AppError from '@shared/errors/AppErrors';

import FakeUsersRepository from '../../repositories/fakes/FakeUserPJRepository';
import UpdateUserPJService from '../UpdateUserPJService';
import CreateUserService from '../CreateUserPJService';
import FakeHashProvider from '../../providers/HashProvider/fakes/FakeHashProvider';

let fakeUsersRepository: FakeUsersRepository;
let fakeHashProvider: FakeHashProvider;
let createUser: CreateUserService;
let updateUser: UpdateUserPJService;

describe('UpdateUserPJService', () => {
  beforeEach(() => {
    fakeUsersRepository = new FakeUsersRepository();
    fakeHashProvider = new FakeHashProvider();
    createUser = new CreateUserService(fakeUsersRepository, fakeHashProvider);
    updateUser = new UpdateUserPJService(fakeUsersRepository, fakeHashProvider);
  });

  it('should be able to update the user data', async () => {
    const createdUser = await createUser.execute({
      firstName: 'John',
      lastName: 'Doe',
      dob: new Date(),
      email: 'johndoe@gmail.com',
      cellphoneArea: '11',
      cellphoneNumber: '99099999399',
      addressStreet: 'Rua de endereço sp',
      addressNumber: '99',
      addressComplement: 'Complemento',
      addressDistrict: 'Jardim Iae',
      addressZipcode: '05890-130',
      addressCity: 'São Paulo',
      addressState: 'SP',
      taxDocumentType: 'CNPJ',
      taxDocumentNumber: '46.256.982/0001-88',
      passwordHash: '123456',
      origens: 'Google',
      credit: 'Marketing',
      value: '4000',
      accountType: 'PJ',
      moipAccountId: 'asfa98fas',
      moipToken: 'asfas908uas',
      ownId: 'afas908f',
      moipCustomerId: 'asjfsaop',
      role: 'PARTNER',
      businessName: '',
      companyAddressCity: 'São Paulo',
      companyAddressComplement: 'Complemento',
      companyAddressDistrict: 'Jardim Iae',
      companyAddressNumber: '99',
      companyAddressState: 'SP',
      companyAddressStreet: 'Rua de endereço sp',
      companyAddressZipcode: '05890-130',
      companyName: 'Firgun',
      companyPhoneArea: '11',
      companyPhoneNumber: '99099999399',
      cpfResponsible: '239.000.000-09',
      emailResponsible: 'johndoe2@gmail.com',
      partnerId: 0,
    });

    const user = await updateUser.execute({
      firstName: 'John',
      lastName: 'Doe',
      dob: new Date(),
      email: 'johndoe@gmail.com',
      cellphoneArea: '11',
      cellphoneNumber: '99099999399',
      addressStreet: 'Rua de endereço sp',
      addressNumber: '99',
      addressComplement: 'Complemento',
      addressDistrict: 'Jardim Iae',
      addressZipcode: '05890-130',
      addressCity: 'São Paulo',
      addressState: 'SP',
      origens: 'Google',
      credit: 'Marketing',
      businessName: '',
      companyAddressCity: 'São Paulo',
      companyAddressComplement: 'Complemento',
      companyAddressDistrict: 'Jardim Iae',
      companyAddressNumber: '99',
      companyAddressState: 'SP',
      companyAddressStreet: 'Rua de endereço sp',
      companyAddressZipcode: '05890-130',
      companyName: 'Firgun',
      companyPhoneArea: '11',
      companyPhoneNumber: '99099999399',
      cpfResponsible: '239.000.000-09',
      emailResponsible: 'johndoe2@gmail.com',
      bankAccountCheckNumber: 324,
      bankAgencyCheckNumber: 32,
      partnerLinkedin: 'www.linkedin.com/dev',
      partnerFacebook: 'www.facebook.com/dev',
      partnerInstagram: 'www.instagram.com/dev',
      partnerYoutube: 'www.youtube.com/dev',
      bankAccountNumber: '2345',
      bankAccountType: 'CHECKING',
      bankAgencyNumber: '342',
      bankNumber: '432',
      companyWebsite: 'www.website.com',
      gender: 'Masculino',
      identityIssueDate: '2020-08-09',
      identityIssuer: 'RG',
      phoneArea: '11',
      phoneNumber: '999999999',
      profession: 'Programador',
      race: 'Pardo',
      userId: createdUser.id,
    });

    expect(user).toHaveProperty('id');
    expect(user.gender).toBe('Masculino');
  });

  it('should not be able to update a non existing user or when an email that exists was taked', async () => {
    await expect(
      updateUser.execute({
        firstName: 'John',
        lastName: 'Doe',
        dob: new Date(),
        email: 'johndoe@gmail.com',
        cellphoneArea: '11',
        cellphoneNumber: '99099999399',
        addressStreet: 'Rua de endereço sp',
        addressNumber: '99',
        addressComplement: 'Complemento',
        addressDistrict: 'Jardim Iae',
        addressZipcode: '05890-130',
        addressCity: 'São Paulo',
        addressState: 'SP',
        passwordHash: '123456',
        origens: 'Google',
        credit: 'Marketing',
        businessName: '',
        companyAddressCity: 'São Paulo',
        companyAddressComplement: 'Complemento',
        companyAddressDistrict: 'Jardim Iae',
        companyAddressNumber: '99',
        companyAddressState: 'SP',
        companyAddressStreet: 'Rua de endereço sp',
        companyAddressZipcode: '05890-130',
        companyName: 'Firgun',
        companyPhoneArea: '11',
        companyPhoneNumber: '99099999399',
        cpfResponsible: '239.000.000-09',
        emailResponsible: 'johndoe2@gmail.com',
        bankAccountCheckNumber: 324,
        bankAgencyCheckNumber: 32,
        partnerLinkedin: 'www.linkedin.com/dev',
        partnerFacebook: 'www.facebook.com/dev',
        partnerInstagram: 'www.instagram.com/dev',
        partnerYoutube: 'www.youtube.com/dev',
        bankAccountNumber: '2345',
        bankAccountType: 'CHECKING',
        bankAgencyNumber: '342',
        bankNumber: '432',
        companyWebsite: 'www.website.com',
        gender: 'Masculino',
        identityIssueDate: '2020-08-09',
        identityIssuer: 'RG',
        phoneArea: '11',
        phoneNumber: '999999999',
        profession: 'Programador',
        race: 'Pardo',
        userId: 4,
      }),
    ).rejects.toBeInstanceOf(AppError);

    await createUser.execute({
      firstName: 'John',
      lastName: 'Doe',
      dob: new Date(),
      email: 'johndoe@gmail.com',
      cellphoneArea: '11',
      cellphoneNumber: '99099999399',
      addressStreet: 'Rua de endereço sp',
      addressNumber: '99',
      addressComplement: 'Complemento',
      addressDistrict: 'Jardim Iae',
      addressZipcode: '05890-130',
      addressCity: 'São Paulo',
      addressState: 'SP',
      taxDocumentType: 'CNPJ',
      taxDocumentNumber: '46.256.982/0001-88',
      passwordHash: '123456',
      origens: 'Google',
      credit: 'Marketing',
      value: '4000',
      accountType: 'PJ',
      moipAccountId: 'asfa98fas',
      moipToken: 'asfas908uas',
      ownId: 'afas908f',
      moipCustomerId: 'asjfsaop',
      role: 'PARTNER',
      businessName: '',
      companyAddressCity: 'São Paulo',
      companyAddressComplement: 'Complemento',
      companyAddressDistrict: 'Jardim Iae',
      companyAddressNumber: '99',
      companyAddressState: 'SP',
      companyAddressStreet: 'Rua de endereço sp',
      companyAddressZipcode: '05890-130',
      companyName: 'Firgun',
      companyPhoneArea: '11',
      companyPhoneNumber: '99099999399',
      cpfResponsible: '239.000.000-09',
      emailResponsible: 'johndoe2@gmail.com',
      partnerId: 0,
    });

    const createdUser = await createUser.execute({
      firstName: 'John',
      lastName: 'Doe',
      dob: new Date(),
      email: 'joh@gmail.com',
      cellphoneArea: '11',
      cellphoneNumber: '99099999399',
      addressStreet: 'Rua de endereço sp',
      addressNumber: '99',
      addressComplement: 'Complemento',
      addressDistrict: 'Jardim Iae',
      addressZipcode: '05890-130',
      addressCity: 'São Paulo',
      addressState: 'SP',
      taxDocumentType: 'CNPJ',
      taxDocumentNumber: '46.256.982/0001-00',
      passwordHash: '123456',
      origens: 'Google',
      credit: 'Marketing',
      value: '4000',
      accountType: 'PJ',
      moipAccountId: 'asfa98fas',
      moipToken: 'asfas908uas',
      ownId: 'afas908f',
      moipCustomerId: 'asjfsaop',
      role: 'PARTNER',
      businessName: '',
      companyAddressCity: 'São Paulo',
      companyAddressComplement: 'Complemento',
      companyAddressDistrict: 'Jardim Iae',
      companyAddressNumber: '99',
      companyAddressState: 'SP',
      companyAddressStreet: 'Rua de endereço sp',
      companyAddressZipcode: '05890-130',
      companyName: 'Firgun',
      companyPhoneArea: '11',
      companyPhoneNumber: '99099999399',
      cpfResponsible: '239.000.000-09',
      emailResponsible: 'johndoe2@gmail.com',
      partnerId: 0,
    });

    await expect(
      updateUser.execute({
        firstName: 'John',
        lastName: 'Doe',
        dob: new Date(),
        email: 'johndoe@gmail.com',
        cellphoneArea: '11',
        cellphoneNumber: '99099999399',
        addressStreet: 'Rua de endereço sp',
        addressNumber: '99',
        addressComplement: 'Complemento',
        addressDistrict: 'Jardim Iae',
        addressZipcode: '05890-130',
        addressCity: 'São Paulo',
        addressState: 'SP',
        passwordHash: '123456',
        origens: 'Google',
        credit: 'Marketing',
        businessName: '',
        companyAddressCity: 'São Paulo',
        companyAddressComplement: 'Complemento',
        companyAddressDistrict: 'Jardim Iae',
        companyAddressNumber: '99',
        companyAddressState: 'SP',
        companyAddressStreet: 'Rua de endereço sp',
        companyAddressZipcode: '05890-130',
        companyName: 'Firgun',
        companyPhoneArea: '11',
        companyPhoneNumber: '99099999399',
        cpfResponsible: '239.000.000-09',
        emailResponsible: 'johndoe2@gmail.com',
        bankAccountCheckNumber: 324,
        bankAgencyCheckNumber: 32,
        partnerLinkedin: 'www.linkedin.com/dev',
        partnerFacebook: 'www.facebook.com/dev',
        partnerInstagram: 'www.instagram.com/dev',
        partnerYoutube: 'www.youtube.com/dev',
        bankAccountNumber: '2345',
        bankAccountType: 'CHECKING',
        bankAgencyNumber: '342',
        bankNumber: '432',
        companyWebsite: 'www.website.com',
        gender: 'Masculino',
        identityIssueDate: '2020-08-09',
        identityIssuer: 'RG',
        phoneArea: '11',
        phoneNumber: '999999999',
        profession: 'Programador',
        race: 'Pardo',
        userId: createdUser.id,
      }),
    ).rejects.toBeInstanceOf(AppError);
  });

  it('should not be able to update when the password was not confirmed', async () => {
    const createdUser = await createUser.execute({
      firstName: 'John',
      lastName: 'Doe',
      dob: new Date(),
      email: 'johndoe@gmail.com',
      cellphoneArea: '11',
      cellphoneNumber: '99099999399',
      addressStreet: 'Rua de endereço sp',
      addressNumber: '99',
      addressComplement: 'Complemento',
      addressDistrict: 'Jardim Iae',
      addressZipcode: '05890-130',
      addressCity: 'São Paulo',
      addressState: 'SP',
      taxDocumentType: 'CNPJ',
      taxDocumentNumber: '46.256.982/0001-88',
      passwordHash: '123456',
      origens: 'Google',
      credit: 'Marketing',
      value: '4000',
      accountType: 'PJ',
      moipAccountId: 'asfa98fas',
      moipToken: 'asfas908uas',
      ownId: 'afas908f',
      moipCustomerId: 'asjfsaop',
      role: 'PARTNER',
      businessName: '',
      companyAddressCity: 'São Paulo',
      companyAddressComplement: 'Complemento',
      companyAddressDistrict: 'Jardim Iae',
      companyAddressNumber: '99',
      companyAddressState: 'SP',
      companyAddressStreet: 'Rua de endereço sp',
      companyAddressZipcode: '05890-130',
      companyName: 'Firgun',
      companyPhoneArea: '11',
      companyPhoneNumber: '99099999399',
      cpfResponsible: '239.000.000-09',
      emailResponsible: 'johndoe2@gmail.com',
      partnerId: 0,
    });

    await expect(
      updateUser.execute({
        firstName: 'John',
        lastName: 'Doe',
        dob: new Date(),
        email: 'johndoe@gmail.com',
        cellphoneArea: '11',
        cellphoneNumber: '99099999399',
        addressStreet: 'Rua de endereço sp',
        addressNumber: '99',
        addressComplement: 'Complemento',
        addressDistrict: 'Jardim Iae',
        addressZipcode: '05890-130',
        addressCity: 'São Paulo',
        addressState: 'SP',
        origens: 'Google',
        credit: 'Marketing',
        businessName: '',
        companyAddressCity: 'São Paulo',
        companyAddressComplement: 'Complemento',
        companyAddressDistrict: 'Jardim Iae',
        companyAddressNumber: '99',
        companyAddressState: 'SP',
        companyAddressStreet: 'Rua de endereço sp',
        companyAddressZipcode: '05890-130',
        companyName: 'Firgun',
        companyPhoneArea: '11',
        companyPhoneNumber: '99099999399',
        cpfResponsible: '239.000.000-09',
        emailResponsible: 'johndoe2@gmail.com',
        bankAccountCheckNumber: 324,
        bankAgencyCheckNumber: 32,
        partnerLinkedin: 'www.linkedin.com/dev',
        partnerFacebook: 'www.facebook.com/dev',
        partnerInstagram: 'www.instagram.com/dev',
        partnerYoutube: 'www.youtube.com/dev',
        bankAccountNumber: '2345',
        bankAccountType: 'CHECKING',
        bankAgencyNumber: '342',
        bankNumber: '432',
        companyWebsite: 'www.website.com',
        gender: 'Masculino',
        identityIssueDate: '2020-08-09',
        identityIssuer: 'RG',
        phoneArea: '11',
        phoneNumber: '999999999',
        profession: 'Programador',
        race: 'Pardo',
        userId: createdUser.id,
        passwordHash: '123456',
      }),
    ).rejects.toBeInstanceOf(AppError);
  });

  it('should not be able to update when the previuos password is wrong', async () => {
    const createdUser = await createUser.execute({
      firstName: 'John',
      lastName: 'Doe',
      dob: new Date(),
      email: 'johndoe@gmail.com',
      cellphoneArea: '11',
      cellphoneNumber: '99099999399',
      addressStreet: 'Rua de endereço sp',
      addressNumber: '99',
      addressComplement: 'Complemento',
      addressDistrict: 'Jardim Iae',
      addressZipcode: '05890-130',
      addressCity: 'São Paulo',
      addressState: 'SP',
      taxDocumentType: 'CNPJ',
      taxDocumentNumber: '46.256.982/0001-88',
      passwordHash: '123456',
      origens: 'Google',
      credit: 'Marketing',
      value: '4000',
      accountType: 'PJ',
      moipAccountId: 'asfa98fas',
      moipToken: 'asfas908uas',
      ownId: 'afas908f',
      moipCustomerId: 'asjfsaop',
      role: 'PARTNER',
      businessName: '',
      companyAddressCity: 'São Paulo',
      companyAddressComplement: 'Complemento',
      companyAddressDistrict: 'Jardim Iae',
      companyAddressNumber: '99',
      companyAddressState: 'SP',
      companyAddressStreet: 'Rua de endereço sp',
      companyAddressZipcode: '05890-130',
      companyName: 'Firgun',
      companyPhoneArea: '11',
      companyPhoneNumber: '99099999399',
      cpfResponsible: '239.000.000-09',
      emailResponsible: 'johndoe2@gmail.com',
      partnerId: 0,
    });

    await expect(
      updateUser.execute({
        firstName: 'John',
        lastName: 'Doe',
        dob: new Date(),
        email: 'johndoe@gmail.com',
        cellphoneArea: '11',
        cellphoneNumber: '99099999399',
        addressStreet: 'Rua de endereço sp',
        addressNumber: '99',
        addressComplement: 'Complemento',
        addressDistrict: 'Jardim Iae',
        addressZipcode: '05890-130',
        addressCity: 'São Paulo',
        addressState: 'SP',
        origens: 'Google',
        credit: 'Marketing',
        businessName: '',
        companyAddressCity: 'São Paulo',
        companyAddressComplement: 'Complemento',
        companyAddressDistrict: 'Jardim Iae',
        companyAddressNumber: '99',
        companyAddressState: 'SP',
        companyAddressStreet: 'Rua de endereço sp',
        companyAddressZipcode: '05890-130',
        companyName: 'Firgun',
        companyPhoneArea: '11',
        companyPhoneNumber: '99099999399',
        cpfResponsible: '239.000.000-09',
        emailResponsible: 'johndoe2@gmail.com',
        bankAccountCheckNumber: 324,
        bankAgencyCheckNumber: 32,
        partnerLinkedin: 'www.linkedin.com/dev',
        partnerFacebook: 'www.facebook.com/dev',
        partnerInstagram: 'www.instagram.com/dev',
        partnerYoutube: 'www.youtube.com/dev',
        bankAccountNumber: '2345',
        bankAccountType: 'CHECKING',
        bankAgencyNumber: '342',
        bankNumber: '432',
        companyWebsite: 'www.website.com',
        gender: 'Masculino',
        identityIssueDate: '2020-08-09',
        identityIssuer: 'RG',
        phoneArea: '11',
        phoneNumber: '999999999',
        profession: 'Programador',
        race: 'Pardo',
        userId: createdUser.id,
        passwordHash: '3432423',
        oldPassword: 'fsafga0s9f',
      }),
    ).rejects.toBeInstanceOf(AppError);
  });

  it('should not be able to update when the password confirmation is wrong', async () => {
    const createdUser = await createUser.execute({
      firstName: 'John',
      lastName: 'Doe',
      dob: new Date(),
      email: 'johndoe@gmail.com',
      cellphoneArea: '11',
      cellphoneNumber: '99099999399',
      addressStreet: 'Rua de endereço sp',
      addressNumber: '99',
      addressComplement: 'Complemento',
      addressDistrict: 'Jardim Iae',
      addressZipcode: '05890-130',
      addressCity: 'São Paulo',
      addressState: 'SP',
      taxDocumentType: 'CNPJ',
      taxDocumentNumber: '46.256.982/0001-88',
      passwordHash: '123456',
      origens: 'Google',
      credit: 'Marketing',
      value: '4000',
      accountType: 'PJ',
      moipAccountId: 'asfa98fas',
      moipToken: 'asfas908uas',
      ownId: 'afas908f',
      moipCustomerId: 'asjfsaop',
      role: 'PARTNER',
      businessName: '',
      companyAddressCity: 'São Paulo',
      companyAddressComplement: 'Complemento',
      companyAddressDistrict: 'Jardim Iae',
      companyAddressNumber: '99',
      companyAddressState: 'SP',
      companyAddressStreet: 'Rua de endereço sp',
      companyAddressZipcode: '05890-130',
      companyName: 'Firgun',
      companyPhoneArea: '11',
      companyPhoneNumber: '99099999399',
      cpfResponsible: '239.000.000-09',
      emailResponsible: 'johndoe2@gmail.com',
      partnerId: 0,
    });

    expect(
      updateUser.execute({
        firstName: 'John',
        lastName: 'Doe',
        dob: new Date(),
        email: 'johndoe@gmail.com',
        cellphoneArea: '11',
        cellphoneNumber: '99099999399',
        addressStreet: 'Rua de endereço sp',
        addressNumber: '99',
        addressComplement: 'Complemento',
        addressDistrict: 'Jardim Iae',
        addressZipcode: '05890-130',
        addressCity: 'São Paulo',
        addressState: 'SP',
        origens: 'Google',
        credit: 'Marketing',
        businessName: '',
        companyAddressCity: 'São Paulo',
        companyAddressComplement: 'Complemento',
        companyAddressDistrict: 'Jardim Iae',
        companyAddressNumber: '99',
        companyAddressState: 'SP',
        companyAddressStreet: 'Rua de endereço sp',
        companyAddressZipcode: '05890-130',
        companyName: 'Firgun',
        companyPhoneArea: '11',
        companyPhoneNumber: '99099999399',
        cpfResponsible: '239.000.000-09',
        emailResponsible: 'johndoe2@gmail.com',
        bankAccountCheckNumber: 324,
        bankAgencyCheckNumber: 32,
        partnerLinkedin: 'www.linkedin.com/dev',
        partnerFacebook: 'www.facebook.com/dev',
        partnerInstagram: 'www.instagram.com/dev',
        partnerYoutube: 'www.youtube.com/dev',
        bankAccountNumber: '2345',
        bankAccountType: 'CHECKING',
        bankAgencyNumber: '342',
        bankNumber: '432',
        companyWebsite: 'www.website.com',
        gender: 'Masculino',
        identityIssueDate: '2020-08-09',
        identityIssuer: 'RG',
        phoneArea: '11',
        phoneNumber: '999999999',
        profession: 'Programador',
        race: 'Pardo',
        userId: createdUser.id,
        passwordHash: '21424',
        oldPassword: '123456',
        passwordConfirmation: 'faasf',
      }),
    ).rejects.toBeInstanceOf(AppError);
  });

  it('should be able to update when the password confirmation is correct', async () => {
    const createdUser = await createUser.execute({
      firstName: 'John',
      lastName: 'Doe',
      dob: new Date(),
      email: 'johndoe@gmail.com',
      cellphoneArea: '11',
      cellphoneNumber: '99099999399',
      addressStreet: 'Rua de endereço sp',
      addressNumber: '99',
      addressComplement: 'Complemento',
      addressDistrict: 'Jardim Iae',
      addressZipcode: '05890-130',
      addressCity: 'São Paulo',
      addressState: 'SP',
      taxDocumentType: 'CNPJ',
      taxDocumentNumber: '46.256.982/0001-88',
      passwordHash: '123456',
      origens: 'Google',
      credit: 'Marketing',
      value: '4000',
      accountType: 'PJ',
      moipAccountId: 'asfa98fas',
      moipToken: 'asfas908uas',
      ownId: 'afas908f',
      moipCustomerId: 'asjfsaop',
      role: 'PARTNER',
      businessName: '',
      companyAddressCity: 'São Paulo',
      companyAddressComplement: 'Complemento',
      companyAddressDistrict: 'Jardim Iae',
      companyAddressNumber: '99',
      companyAddressState: 'SP',
      companyAddressStreet: 'Rua de endereço sp',
      companyAddressZipcode: '05890-130',
      companyName: 'Firgun',
      companyPhoneArea: '11',
      companyPhoneNumber: '99099999399',
      cpfResponsible: '239.000.000-09',
      emailResponsible: 'johndoe2@gmail.com',
      partnerId: 0,
    });

    expect(
      await updateUser.execute({
        firstName: 'John',
        lastName: 'Doe',
        dob: new Date(),
        email: 'johndoe@gmail.com',
        cellphoneArea: '11',
        cellphoneNumber: '99099999399',
        addressStreet: 'Rua de endereço sp',
        addressNumber: '99',
        addressComplement: 'Complemento',
        addressDistrict: 'Jardim Iae',
        addressZipcode: '05890-130',
        addressCity: 'São Paulo',
        addressState: 'SP',
        origens: 'Google',
        credit: 'Marketing',
        businessName: '',
        companyAddressCity: 'São Paulo',
        companyAddressComplement: 'Complemento',
        companyAddressDistrict: 'Jardim Iae',
        companyAddressNumber: '99',
        companyAddressState: 'SP',
        companyAddressStreet: 'Rua de endereço sp',
        companyAddressZipcode: '05890-130',
        companyName: 'Firgun',
        companyPhoneArea: '11',
        companyPhoneNumber: '99099999399',
        cpfResponsible: '239.000.000-09',
        emailResponsible: 'johndoe2@gmail.com',
        bankAccountCheckNumber: 324,
        bankAgencyCheckNumber: 32,
        partnerLinkedin: 'www.linkedin.com/dev',
        partnerFacebook: 'www.facebook.com/dev',
        partnerInstagram: 'www.instagram.com/dev',
        partnerYoutube: 'www.youtube.com/dev',
        bankAccountNumber: '2345',
        bankAccountType: 'CHECKING',
        bankAgencyNumber: '342',
        bankNumber: '432',
        companyWebsite: 'www.website.com',
        gender: 'Masculino',
        identityIssueDate: '2020-08-09',
        identityIssuer: 'RG',
        phoneArea: '11',
        phoneNumber: '999999999',
        profession: 'Programador',
        race: 'Pardo',
        userId: createdUser.id,
        passwordHash: '123123',
        passwordConfirmation: '123123',
        oldPassword: '123456',
      }),
    ).toHaveProperty('id');
  });
});
